### ISSUE TITLE
useExhaustiveDependencies: add option for automatically 

### ISSUE THREAD

**Issue by vanch3d** [biomejs/biome-intellij#1]
Great beginning with the plugin. Looking forward to definitely switching to `biome`

One issue I found a little bit annoying, compared to the `ESLint` plugin. 
In the context of a `React` `useEffect` (I haven't tried it in any other cases), the plugin easily finds any missing dependencies on the hook:

```js
  useEffect(() => {
    if ((state) {
      setOtherState(state)    
   }
  }, [])
``` 

But the plugin offers me only one option: suppress the rule: 

![Screenshot 2023-12-15 at 11 18 14](https://github.com/biomejs/biome-intellij/assets/2743481/1a98f877-7391-4760-9e16-1700dc45f9d5)

What is missing is at least another option to automatically update the dependency array: 

![Screenshot 2023-12-15 at 12 57 36](https://github.com/biomejs/biome-intellij/assets/2743481/6e216fdb-1fad-4010-8ede-c1b097bcbe30)

Running `biome check` indicates in the console the vars that are missing so the information is already there.

#### Note
- `Webstorm` version `2023.3`
- `biome` plugin version `0.0.7`

**Comment by ematipico** [comment]
Hi @vanch3d , I would suggest to open a discussion in the main repo `biomejs/biome`, maybe here: https://github.com/biomejs/biome/discussions/3

We control code actions via LSP, not the plugin. If a code action is implemented in core, the plugin will automatically display it. That's the beauty of supporting LSP :)

**Comment by srosato** [comment]
@ematipico How can I determine if the code action is implemented? I went on https://github.com/biomejs/biome/discussions/3 and saw green checks for `useExhaustiveDependencies`

![image](https://github.com/biomejs/biome-intellij/assets/650192/a409bbf9-57a7-4e13-b200-c8908cbd6b1a)

But when I enable the rule like this:

```json
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": false,
      "correctness": {
        "useExhaustiveDependencies": "warn"
      }
    },
``` 

and restart the LSP server, I do not get suggestions to fix dependencies from IntelliJ.

![image](https://github.com/biomejs/biome-intellij/assets/650192/da599c39-90eb-45e8-bfef-c9e1c3079881)

I would assume its not yet implemented, but I wonder where I can validate if its implemented or not?

Thanks!

**Comment by ematipico** [comment]
You're actually correct. If the website doesn't show the emoji for the autofix, it means it doesn't have it
