### ISSUE TITLE
IntelliJ IDEA 2024.3 only installs version 1.0.0

### ISSUE THREAD

**Issue by Pascalmh** [biomejs/biome-intellij#101]
After upgrading to from `2024.2.4` to `2024.3` the Biome plugin was downgraded from `1.4.0` to `1.0.0`.

![image](https://github.com/user-attachments/assets/828cd343-4b20-48c2-8b1c-a2315ced5a99)

**Comment by APshenkin** [comment]
@ematipico Seems starting this PR max version was added
https://github.com/biomejs/biome-intellij/pull/48/files

So we face this issue each release of Intellij IDE. Maybe it's good idea to remove it?

**Comment by denbezrukov** [comment]
I'm not sure because there is no guarantee that they're compatible

**Comment by APshenkin** [comment]
@denbezrukov Intellij send compile errors for upcoming versions to plugin owner email. So in theory you can track those breaking changes without need to bump supported version all the time. Of course it will only work if those reports will be handled in time.

**Comment by denbezrukov** [comment]
@APshenkin 
Thank you!
I didn't know about that!
