### ISSUE TITLE
java.lang.AssertionError: Wrong line separators

### ISSUE THREAD

**Issue by david-peherstorfer** [biomejs/biome-intellij#108]
We are trying to use the biome-intellij plugin in RustRuver under Windows.
When using the Action "Reformat with Biome" we get the following error and nothing happens.
This only happens the first time trying this afterwards we need to do a restart of RustRover to trigger the error again.

It looks similar to this issue:
https://github.com/biomejs/biome-intellij/issues/52

This is the stack trace:
`java.lang.AssertionError: Wrong line separators: '...uvr-rust';\r\nimport {...' at offset 74    at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2560)    at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:739)    at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:629)    at com.intellij.openapi.editor.impl.DocumentImpl.lambda$setText$6(DocumentImpl.java:1109)    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:217)    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)    at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:1114)    at com.github.biomejs.intellijbiome.actions.BiomeCheckRunner.applyChanges$lambda$6(BiomeCheckRunner.kt:91)    at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:147)    at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction$lambda$5(AnyThreadWriteThreadingSupport.kt:379)    at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:389)    at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:379)    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:896)    at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:145)    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)    at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:154)    at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$run$0(WriteCommandAction.java:125)    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)    at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)    at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)    at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)    at com.intellij.openapi.application.impl.AppImplKt.rethrowExceptions$lambda$2(appImpl.kt:57)    at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)    at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)    at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)    at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)    at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)    at com.intellij.openapi.application.impl.AppImplKt.rethrowExceptions$lambda$3(appImpl.kt:68)    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:102)    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)    at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)    at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)    at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)    at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)    at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)    at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)    at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)    at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)    at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)    at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)    at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)    at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)    at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)`

**Comment by denbezrukov** [comment]
@david-peherstorfer Hi,
What version of the plugin do you use?

**Comment by denbezrukov** [comment]
Could you try to use the night version?
https://plugins.jetbrains.com/plugin/22761-biome/versions/nightly/649102
