### ISSUE TITLE
🐛 IntelliJ Format Action - Exception on exec

### ISSUE THREAD

**Issue by John-Paul-R** [biomejs/biome-intellij#12]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.18.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

Using the [Biome IntelliJ Plugin](https://plugins.jetbrains.com/plugin/22761-biome) with format-on-save.

### IntelliJ Plugin Settings

Biome CLI Path

```
/home/jp-kcf/.local/share/pnpm/biome
```

biome.json Directory Path

```
/home/jp-kcf/kcf/Odyssey-Frontend/figma_tokens_formatter/
```

### IntelliJ-Reported Exception

This occurs on-save. (I have Reformat on Save enabled)

No formatting occurs.

```
Formatting error
/home/my_user/.local/share/pnpm/biome:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^ SyntaxError: missing ) after argument list at internalCompileFunction (node:internal/vm:77:18) at wrapSafe (node:internal/modules/cjs/loader:1288:20)
at Module._compile (node:internal/modules/cjs/loader:1340:27) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
at node:internal/main/run_main_module:28:49 Node.js v21.4.0
```

### Expected result

It should not throw an error. Formatting should occur.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by victor-teles** [comment]
@John-Paul-R Thank you for reporting!

All other functionalities are working except for the reformat on save? (like linting)

**Comment by John-Paul-R** [comment]
@victor-teles It's hard to tell. I definitely am getting no linting, but there are no observable error messages with respect to that.

I am uncertain if there is additional configuration I am missing... Going through the plugin page, `ALT+Enter` also does nothing. (though maybe that requires the linter to be active)


Running `biome lint ./*.ts` via cli explicitly does yield the expected linting results, however:

```
  ✖ The assignment should not be in an expression.
  
    68 │     idx = 0,
    69 │ ): PathTree<TVal> {
  > 70 │     const target = (obj[path[idx]] = obj[path[idx]] ?? {});
       │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    71 │     if (idx >= path.length - 2) {
    72 │         return target;
  
  ℹ The use of assignments in expressions is confusing.
    Expressions are often considered as side-effect free.
  

./figma_tokens_formatter.ts lint ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ The file contains diagnostics that needs to be addressed.

```

**Comment by John-Paul-R** [comment]
for good measure, using the exact same specified binary, explicitly: `/home/jp-kcf/.local/share/pnpm/biome lint ./*.ts` does indeed yield the correct results via the CLI.

**Comment by victor-teles** [comment]
@John-Paul-R Thank you for the extra informations!
 I'll investigate it
