### ISSUE TITLE
Allow Disabling Biome Plugin

### ISSUE THREAD

**Issue by gabrielmcreynolds** [biomejs/biome-intellij#17]
Currently in Biome settings there is no option to disable this plugin. 

### Why is this needed
I work on multiple projects, some use Biome and some use Prettier. Currently, Biome is preventing me from formatting my code in Prettier projects. Even with "Run on 'Reformat Code' action" toggled on in Prettier settings, Biome is still run on format throwing error: "Biome language server is not found, make sure you have @biomejs/biome installed."

### What I want
 What I need is there to be an checkbox in Settings for Biome to disable Biome similar to how Prettier has an option to Disable Prettier.

**Comment by victor-teles** [comment]
@gabrielmcreynolds We implemented this feature and we are planning to release it very soon 🤞

**Comment by gabrielmcreynolds** [comment]
@victor-teles Thanks for the quick response. Do you have a timeframe for the release?

**Comment by victor-teles** [comment]
@gabrielmcreynolds I going to release a nightly version today.
And the stable version on the next 1-2 weeks (I need to test the new version on Windows to ensure everything is working fine)
