### ISSUE TITLE
Add support for LSP API

### ISSUE THREAD

**Issue by cjthompson** [biomejs/biome-intellij#22]
The latest IntelliJ releases add support for [Language Server Protocol (LSP) for Plugin Developers](https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/).

Documentation [is here](https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html) and an example [is here](https://github.com/JetBrains/intellij-plugins/tree/master/prisma/src/org/intellij/prisma/ide/lsp).

Would Biome be able to replace the TypeScript LSP?

**Comment by ematipico** [comment]
The plugin already [uses the LSP APIs ](https://github.com/biomejs/biome-intellij/blob/dba5d5df23adcc5e71d35c6794e9623663b82fb0/src/main/kotlin/com/github/biomejs/intellijbiome/widgets/BiomeWidget.kt#L7)

>Would Biome be able to replace the TypeScript LSP?

That's the grand goal, yes
