### ISSUE TITLE
Support for 'organizeImports'

### ISSUE THREAD

**Issue by oferitz** [biomejs/biome-intellij#23]
Thank you for the plugin! I'm using v1-nightly, along with Biome 1.5.1.

In my biome.json file, I have enabled organizeImports:
```json
  "organizeImports": {
    "enabled": true
  }
```
However, neither the safe fix nor the formatting commands have any effect on the import order. Am I missing something, or is this not supported yet?

**Comment by victor-teles** [comment]
This is not currently supported because the plugin uses `biome lint` and `biome format` and the `organize imports` seem to only work with `biome check` and `biome ci` commands.
