### ISSUE TITLE
Feature request: Highlight formatting changes

### ISSUE THREAD

**Issue by martinbiard** [biomejs/biome-intellij#38]
### Context

I'm currently in the process of attempting to migrate from eslint/prettier to biome. I am using plugin version Biome-1.0.0-nightly.14eb397 with Biome version 1.5.3.

### Feature Request

Unless there is already a way that I am unaware of, I would like to request an option on the plugin that implements the highlighting of code flagged for formatting, in the same way as is possible with eslint/prettier (see screenshot).

### Reasons

I prefer to disable any automatic formatting and see the issues flagged in the editor instead. The visual flagging of code that needs a reformat lets me know that there are issues and I remain in control to decide when to reformat the whole file, or only part of the code, using the Ctrl-Alt-L shortcut.

![eslint_prettier](https://github.com/biomejs/biome-intellij/assets/5204353/36b0432e-5d30-4425-9546-67434b4c472f)

**Comment by ematipico** [comment]
Hey @martinbiard 

FYI, this isn't a feature provided by the extension but by the LSP. 

I am going to close this issue for now, feel free to jump in https://github.com/biomejs/biome/discussions/809
