### ISSUE TITLE
Support RustRover

### ISSUE THREAD

**Issue by Eatham532** [biomejs/biome-intellij#55]
Would love to see this plugin also supported in RustRover

![image](https://github.com/biomejs/biome-intellij/assets/78714349/74032541-7bf4-4436-8c5b-f9cb64b00969)

**Comment by ematipico** [comment]
Wanna send a PR?

**Comment by Eatham532** [comment]
@ematipico Would like to but I have no experience with developing JetBrains plugins. I managed to get it working on RustRover by installing it manually. So you may need to configure the plugin on the JetBrains plugin site

**Comment by ematipico** [comment]
I use RustRover and I have the plugin installed. Are you trying to install an old version @Eatham532  ?

**Comment by Eatham532** [comment]
@ematipico I have the latest version of RustRover and tried to install the latest version of the plugin. It doesnt even come up when I search within the IDE

**Comment by ematipico** [comment]
The latest version of RustRover removed the support for the `JavaScript` module. Without this module, the Biome plugin cant' work. Unless RustRover adds it, we can't do much.

**Comment by JohannesIBK** [comment]
RustRover has the `JavaScript Base` bundled, is it feasable to support this?

**Comment by ematipico** [comment]
Do you have a link to it? I don't know if it's feasible. I don't have prior knowledge. But I would welcome a PR for it

**Comment by ematipico** [comment]
https://youtrack.jetbrains.com/issue/RUST-14337
