### ISSUE TITLE
Biome formatter prevents IntelliJ formatter to run even if disabled

### ISSUE THREAD

**Issue by toverux** [biomejs/biome-intellij#62]
First, thanks for bringing Biome to IntelliJ IDEs!

I have an issue with the formatter, I'd like to disable it on .js files because I prefer how my IDE config handles formatting.

Unfortunately, whether I put `"formatter": false` a the root of the config or just in the `"javascript":` block, IntelliJ formatter is still bypassed: it says "Running LSP-based formatter" in the status bar and my settings aren't applied unless I disable Biome plugin entirely. Of course Biome itself honors the setting, so no formatting is done at all.

This forces me to either abandon the Biome plugin or my formatting preferences (did the second because linting in-editor is precious, but I'm quite unhappy with Prettier-style formatting).

**Comment by cmattick** [comment]
I am currently evaluating to move from typscript eslint to biome since i have massive performance problems with that setup. Unfortuanetly I have the same issue with the IDE formatter which is apparently disabled completely on activating the biome plugin in the settings. Is there any chance to get that fixed soon?

Maybe a useful note: If i check the "Run format on save" checkbox the biome formatter is running despite I have disabled the formatter in the options. My config which i am testing with looks like this:

```
{
	"$schema": "https://biomejs.dev/schemas/1.9.0/schema.json",
	"formatter": {
		"enabled": false
	},
	"linter": {
		"enabled": true,
		"rules": {
			"style": {
				"useImportType": "off",
				"noUselessElse": "off"
			},
			"correctness": {
				"noGlobalObjectCalls": "off"
			},
			"suspicious": {
				"noExplicitAny": "off"
			}
		}
	},
	"organizeImports": {
		"enabled": false
	}
}
```

**Comment by cmattick** [comment]
Additional note: As a workaround I found that changing the IDEs Reformat on save from "whole file" to "changed lines" works.

**Comment by kpietraszko** [comment]
Note that an empty Biome error shows up in the notifications panel when you try to run JetBrains' formatter with `"formatter": false`.

In my opinion, there should be a checkbox "Run on 'Reformat Code' action" like in the Prettier plugin, see here: https://www.jetbrains.com/help/idea/prettier.html#ws_prettier_configure

**Comment by denbezrukov** [comment]
Could you try please to use the night build?
https://plugins.jetbrains.com/plugin/22761-biome/versions/nightly

We removed "reformat on save" and added "Enable LSP-based code formatting" in settings.

**Comment by cmattick** [comment]
I tried Biome 1.5.2-nightly.4b695b7, that fixes the problem. Thank you!
