### ISSUE TITLE
Infinite indexing / intellisense blocked

### ISSUE THREAD

**Issue by kubijo** [biomejs/biome-intellij#66]
Lately, the plugin causes the IDE to be absolutely unusable.
- Indexing takes ages to complete and not much works when indexing is active
- even when not indexing, the IDE seems stuck in some zombie state where
  - `Go to File…` doesn't do anything
  - these overlay action dialogs (like `Go to File…`) often get stuck at some partial opacity
  - syntax highlighting and `go to definition` doesn't work`

…plus it [still keeps crashing often](https://github.com/biomejs/biome-intellij/issues/39)

# `biome rage`

```
CLI:
  Version:                      1.8.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.1.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/4.2.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

# IDE Info

```
PyCharm 2024.1.3 (Professional Edition)
Build #PY-241.17890.14, built on June 4, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.8.0-35-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  ide.text.fractional.metrics=[Auto|Disabled*|Enabled]
  editor.text.fractional.metrics=[Auto|Disabled*|Enabled]
  ide.experimental.ui=true
Non-Bundled Plugins:
  de.achimonline.tempconfigcleaner (1.6.2)
  nix-idea (0.4.0.14)
  idea.plugin.protoeditor (241.15989.49)
  lermitage.intellij.extra.icons (2024.4.2)
  name.kropp.intellij.makefile (241.14494.150)
  com.vecheslav.darculaDarkerTheme (1.2.0)
  com.github.leomillon.uuidgenerator (4.5.1)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  io.nimbly.tzatziki (17.4.0)
  String Manipulation (9.14.1)
  ICU (1.1.0)
  Dummy Text Generator (1.2.0)
  mobi.hsz.idea.gitignore (4.5.3)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  mdx.js (241.15989.9)
  cucumber-javascript (241.14494.140)
  com.github.bufbuild.intellij (0.4.1)
  zielu.gittoolbox (500.2.9+233)
  com.github.lppedd.idea-return-highlighter (0.8.3)
  com.koxudaxi.ruff (0.0.33)
  com.github.copilot (1.5.7.5758)
  io.aesy.yamllint (0.4)
  ru.adelf.idea.dotenv (2024.1)
Current Desktop: ubuntu:GNOME
```

**Comment by kubijo** [comment]
I verified that it is indeed caused by this plugin by disabling it when it got to this stuck state, and it all went ok in seconds.
One of the trigger points seems to be a git branch switch.

**Comment by martin-probst** [comment]
I can confirm this behavior is reproducible when using yarn modern with pnp (plug 'n play) node linking (no more node_modules dependency folders). IntelliSense stops working, indexing hangs, cpu load goes insane. Disable the biome plugin and everything is working as usual again within seconds. Using yarn modern with the old linking strategy (with node_modules) still seems to work.

**Comment by aristofun** [comment]
Same here on pnpm monorepo anytime you update/install dependencies - JetBrains freezes completely for dozens of seconds on m1pro mac
