### ISSUE TITLE
Refresh README

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome-intellij#7]
The README could probably use a refresh.

Idea is to make it look similar to the one we have in [biomejs/biome-vscode](https://github.com/biomejs/biome-vscode)

- title
- badges
- description
- key features
- installation instructions
- getting started
- usage
- settings
- compatibility matrix

Contribution section can go, as we now have a dedicated contribution guide.

**Comment by andreluiz901** [comment]
hello @nhedger , hdy?

its just a visual update at README.md? I recently update my own readme with some styles, colors, etc. and i tink i could help. 
However i never did any contribution here. but, i think i could help with this. 

Can you let this job to me? im reading the contributing.md now.

**Comment by nhedger** [comment]
Hey @andreluiz901,

I appreciate your interest and am happy to assign you to the issue.

It's not only a visual update of the readme; we are trying to make it consistent with the one we have for [biomejs/biome-vscode](https://github.com/biomejs/biome-vscode), from which you can inspire yourself.

I suggest you fork the repo and create a draft PR as soon as possible so we can quickly provide feedback while you work on this.

Cheers

**Comment by andreluiz901** [comment]
Thanks @nhedger , i ll fork right now and start a draft PR.

**Comment by andreluiz901** [comment]
I created a draft [PR](https://github.com/biomejs/biome-intellij/pull/10) now with initial changes. I am not sure how can i do more updates or what to put in examples, usages and compatibility matrix. I would appreciatte any feedback. 

- [x ] title
- [ x]  badges
- [ x] description
- [ x] key features
- [x ] installation instructions
- [x ]  getting started
- [ ] usage
- [x ] settings
- [ ] compatibility matrix
