### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome-intellij#8]
We should add the following two licenses to the repository:

- MIT
- Apache 2.0

**Comment by ematipico** [comment]
MIT or Apache 2.0. Would that be possible?

**Comment by nhedger** [comment]
Assuming all contributors are OK, I don't see why not.

---

In favor of relicensing from `MIT` to `MIT or Apache 2.0` ?

- [ ] @victor-teles  
- [ ] @SuperchupuDev 
- [ ] @nissy-dev
- [ ] @ematipico
- [x] @nhedger
