### ISSUE TITLE
Improve JetBrains Marketplace plugin description

### ISSUE THREAD

**Issue by rakleed** [biomejs/biome-intellij#92]
Please improve [JetBrains Marketplace plugin](https://plugins.jetbrains.com/plugin/22761-biome) description:

- Add information about what is Biome, not just link[^1]
- Update `Source code` link to [github.com/biomejs/biome-intellij](https://github.com/biomejs/biome-intellij)[^2]
- Add a few screenshots[^3]
- Include change notes in every release[^4]
- Add documentation URL and bugtracker[^5]
- Add a donation link[^6]

[^1]: https://plugins.jetbrains.com/docs/marketplace/best-practices-for-listing.html#plugin-description
[^2]: https://plugins.jetbrains.com/docs/marketplace/best-practices-for-listing.html#plugin-compatibility
[^3]: https://plugins.jetbrains.com/docs/marketplace/best-practices-for-listing.html#media
[^4]: https://plugins.jetbrains.com/docs/marketplace/best-practices-for-listing.html#change-notes
[^5]: https://plugins.jetbrains.com/docs/marketplace/best-practices-for-listing.html#contacts-and-resources
[^6]: https://plugins.jetbrains.com/docs/marketplace/best-practices-for-listing.html#donations

**Comment by ematipico** [comment]
PRs are welcome, any help is appreciated
