### ISSUE TITLE
Quick Fix not showing up in Webstorm 2024.2.1

### ISSUE THREAD

**Issue by cmattick** [biomejs/biome-intellij#93]
I can't get the manual Quick Fix working in Webstorm 2024.2.1 (grayed out). Do you have any hints for me or is this a bug?

**Comment by nhedger** [comment]
Any chance you're on Biome 1.9.0 ? We've had issues with quick fixes and published 1.9.1 to address the issue

**Comment by cmattick** [comment]
Yes, indeed. Problem went away with 1.9.1, thanks alot.

**Comment by cmattick** [comment]
I also tried 1.9.2 and the issue occurred again.

**Comment by denbezrukov** [comment]
Hi!

The fix is expected to land in the 2024.3 WebStorm release.

There is no workaround for the issue except to downgrade the Biome version.
